suffix:
  - ""
  - "-novec"
c_compiler:                # [win]
  - vs2022                 # [win]
cxx_compiler:              # [win]
  - vs2022                 # [win]
# we pinned to cxx_compiler_version 19.40
# on windows to workaround issues with 19.41 in 2024/09/02
# https://github.com/conda-forge/onnxruntime-feedstock/pull/127#issuecomment-2324265203
cxx_compiler_version:      # [win]
  - 19.40                  # [win]
