c_stdlib_version:          # [osx and x86_64]
- '10.15'                  # [osx and x86_64]
suffix:
- ''
- -novec

github_actions_labels:          # [linux or win]
- cirun-openstack-cpu-2xlarge   # [linux]
- cirun-azure-windows-4xlarge   # [win]
