# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on:
  push:

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 720
    strategy:
      fail-fast: false
      matrix:
        include:
          - CONFIG: linux_64_cuda_compiler_version12.9python3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_h3a66bdde', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_version12.9python3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_h31d65d89', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_version12.9python3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_hc301f952', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_version12.9python3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_hca068e97', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_version12.9python3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_h562205ff', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_version12.9python3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_hfcb0a960', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_version12.9python3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_h5ed9d557', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_version12.9python3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9python_h1cca7428', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_h324bf040', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_h880ce673', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_h6ac1d39a', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_h7de3e2a5', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_hec45729e', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_h054a5f3a', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_h8b4dbaa6', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonepython3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_64_cuda_compiler_versionNonepython_h22789aa6', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_h02b92a48', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_h29ebf758', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_h50dfbc70', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_hbd10c3ea', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_h956d8279', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_hc525edcf', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_h17d71111', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonepython3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-4xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNonep_ha614c754', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: win_64_cuda_compiler_version12.9python3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._haca5f550', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.9python3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._hda3d5d91', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.9python3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._h2845a0b2', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.9python3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._hf5f00a0b', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.9python3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._h39d4b130', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.9python3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._h512b08c8', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.9python3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._h3665483b', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.9python3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_version12.9python3._hc205d925', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h9b8b909e', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._hb247aade', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h6928eed6', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h4390b1c1', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h7ca8fcdb', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h7e77335f', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h4998f419', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-azure-windows-4xlarge--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._he08fd93b', 'windows', 'x64', 'self-hosted']
    steps:

    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Build on Linux
      id: build-linux
      if: matrix.os == 'ubuntu'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        CI: github_actions
        CONDA_FORGE_DOCKER_RUN_ARGS: "${{ matrix.CONDA_FORGE_DOCKER_RUN_ARGS }}"
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          echo "::group::Configure binfmt_misc"
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        fi
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        echo "::endgroup::"
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      id: build-macos
      if: matrix.os == 'macos'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        CI: github_actions
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Build on windows
      id: build-windows
      if: matrix.os == 'windows'
      shell: cmd
      run: |
        set "flow_run_id=github_%GITHUB_RUN_ID%"
        set "remote_url=https://github.com/%GITHUB_REPOSITORY%"
        set "sha=%GITHUB_SHA%"
        call ".scripts\run_win_build.bat"
      env:
        # default value; make it explicit, as it needs to match with artefact
        # generation below. Not configurable for now, can be revisited later
        CONDA_BLD_DIR: C:\bld
        MINIFORGE_HOME: D:\Miniforge
        PYTHONUNBUFFERED: 1
        CONFIG: ${{ matrix.CONFIG }}
        CI: github_actions
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}