# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on:
  push:

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_h8f0667df', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_h79cd68f9', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_h35b6644d', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_hf51fbe0a', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_hf0551f3f', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_hddb3238e', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_h83b75940', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version13cuda_compil_hdbfbedcf', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_hb6ff45a4', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_h8d244d99', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_h72e90ebc', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_h6c2a36ac', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_hab2d2070', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_hd0fd9bbe', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_h9ee873a5', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_c_compiler_version14cuda_compil_h12cfc682', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_h9af13a35', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_ha09c1152', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_h449e9073', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_he349cd41', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_h33420b4e', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_h1e75c685', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_h5f4788cd', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version13cuda_compiler_version12.6cxx_compiler_version13python3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version13cuda_c_hdb228773', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_hc2bf79b6', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.10.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_hcdd232d6', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_h8454391f', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.11.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_hc6fa82d0', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_h85934adc', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.12.____cpythonsuffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_h05b1e562', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_hbfca3cbe', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_c_compiler_version14cuda_compiler_versionNonecxx_compiler_version14python3.13.____cp313suffix-novec
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_c_compiler_version14cuda_c_h98542a0a', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: win_64_cuda_compiler_version12.6python3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_version12.6python3._h1ff4ab20', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.6python3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_version12.6python3._h9b18927f', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.6python3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_version12.6python3._hfe97c7d8', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_version12.6python3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_version12.6python3._h8fbd836a', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.10.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h9b8b909e', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.11.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h6928eed6', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.12.____cpythonsuffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h7ca8fcdb', 'windows', 'x64', 'self-hosted']
          - CONFIG: win_64_cuda_compiler_versionNonepython3.13.____cp313suffix
            UPLOAD_PACKAGES: True
            os: windows
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-win_64_cuda_compiler_versionNonepython3._h4998f419', 'windows', 'x64', 'self-hosted']
    steps:

    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Build on Linux
      id: build-linux
      if: matrix.os == 'ubuntu'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        CI: github_actions
        CONDA_FORGE_DOCKER_RUN_ARGS: "${{ matrix.CONDA_FORGE_DOCKER_RUN_ARGS }}"
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          echo "::group::Configure binfmt_misc"
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        fi
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        echo "::endgroup::"
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      id: build-macos
      if: matrix.os == 'macos'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        CI: github_actions
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Build on windows
      id: build-windows
      if: matrix.os == 'windows'
      shell: cmd
      run: |
        set "flow_run_id=github_%GITHUB_RUN_ID%"
        set "remote_url=https://github.com/%GITHUB_REPOSITORY%"
        set "sha=%GITHUB_SHA%"
        call ".scripts\run_win_build.bat"
      env:
        # default value; make it explicit, as it needs to match with artefact
        # generation below. Not configurable for now, can be revisited later
        CONDA_BLD_DIR: C:\bld
        MINIFORGE_HOME: D:\Miniforge
        PYTHONUNBUFFERED: 1
        CONFIG: ${{ matrix.CONFIG }}
        CI: github_actions
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}